"""uninfo_map

迁移 ID: 25c9e3af1647
父迁移: 71a72119935f
创建时间: 2024-10-26 16:41:09.839653

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "25c9e3af1647"
down_revision: str | Sequence[str] | None = "71a72119935f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_session_orm_sessiontouninfomap",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("uninfo_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_nonebot_plugin_session_orm_sessiontouninfomap")
        ),
        sa.UniqueConstraint("session_id", "uninfo_id", name="unique_map"),
        info={"bind_key": "nonebot_plugin_session_orm"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_session_orm_sessiontouninfomap")
    # ### end Alembic commands ###
