"""constraint_name

迁移 ID: 2e0c173949d3
父迁移: 71a72119935f
创建时间: 2024-12-28 19:32:20.483764

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "2e0c173949d3"
down_revision: str | Sequence[str] | None = "71a72119935f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_session_orm_sessionmodel", schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            "unique_session",
            type_="unique",
        )
        batch_op.create_unique_constraint(
            "nonebot_plugin_session_orm_unique_session",
            [
                "bot_id",
                "bot_type",
                "platform",
                "level",
                "id1",
                "id2",
                "id3",
            ],
        )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_session_orm_sessionmodel", schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            "nonebot_plugin_session_orm_unique_session",
            type_="unique",
        )
        batch_op.create_unique_constraint(
            "unique_session",
            [
                "bot_id",
                "bot_type",
                "platform",
                "level",
                "id1",
                "id2",
                "id3",
            ],
        )
    # ### end Alembic commands ###
